# Project information
site_name: Opensource Spain Guides
site_url: https://opensource-spain-guides.github.io/
site_description: >-
  An open-source collection of guides and resources for living and 
  working in Spain: visas, taxes, and daily life tips.

# Repository
repo_name: opensource-spain-guides/osg-site
repo_url: https://github.com/opensource-spain-guides/osg-site
edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.view
    - content.action.edit
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Guides:
    - guides/index.md
    - guides/guide-digital-certificate.md

extra:
  analytics:
    provider: custom
    property: foobar
